title: How big can Big text be?
description: Looking at how type is used in gigantic lettering
header_text: ""
footer_text: Copyright 2020 Chris Jennings
header_feature_image: ../uploads/bigtext.jpg
bannerheight: 100vh
logo: ../uploads/btlogo.png
favicon: ../uploads/favicon.ico
gridlayout: false
fixednavbar: true
upzoom: true
items:
  - name: Chris Jennings
    siteurl: /aboutme/
