title: How big can Big text be?
description: Looking at how type is used in gigantic lettering
header_text: Lettering for Giants
footer_text: Copyright 2020 Chris Jennings
header_feature_image: ../uploads/bigtext.jpg
bannerheight: 10vmax
logo: ../uploads/btlogo.png
favicon: ../uploads/favicon.ico
gridlayout: true
fixednavbar: true
upzoom: true
items: []
